reanahub/reana-commons

- reana_commons/models.py
* ADD engine generic fields [planned, submitted,
succeeded, failed], and a general purpose JSON type field,
to capture the run progress.
> models: Run table refactoring

- setup.py
* `fs>=2.0` has a conflict with current invenio-records-rest whose
latest supported version of `fs` is <2.0.
> installation: decrease minimum version of fs

- reana_commons/utils.py
* Changes digest to hexdigest which I accidentally removed from
d1f01fb6bd345b15679fc83a1368b3eb5a249e1d while rebasing.
> utils: hexdigest to calculate inputs hash

- reana_commons/models.py
- reana_commons/utils.py
* ADD calculate_file_access_time() methods in utils to return dict
of workspace files and their last access times.
* ADD clean job_spec by removing workflow workspace that is unique.
> models: addition of access times in job cache

- reana_commons/models.py
- reana_commons/utils.py
* Changes how user workspace is built, removes `organization` and
renames `analyses` to `workflow_runs`
(connect reanahub/reana-workflow-controller#108).
> models: move user's workspace path build logic to models

- reana_commons/serial.py
- setup.py
* Moves Serial spec schema from REANA Client to here.
* Includes logic to validate and expand Serial spec parameters so
this can be used both in client and server side (REANA Workflow
Engine Serial) (closes reanahub/reana-workflow-engine-serial#34).
> serial: include serial spec loading logic

- reana_commons/utils.py
- setup.py
* Removes `fs` dependency that is not used anymore. (closes #18)
> installation: removal of `fs` dependency

- reana_commons/version.py
- setup.py
* Upgrades Click since its new minimum version in `bravado` changed
to `7.0`.
* Includes `jsonschema` extra dependency on `format` because if we
pin it without the extra the dependency is overwritten and format
is missing for `bravado-core`.
> installation: upgrade Click version

- AUTHORS.rst
- reana_commons/config.py
* Changing default reana_server_url value from None to valid url,
because initialization of SwaggerClient with swagger_spec.api_url
as None fails.
Co-authored-by: Diego Rodriguez <diego.rodriguez@cern.ch>
> config: amend config

- reana_commons/utils.py
- reana_commons/version.py
* Automatic freshly generated and validated openapi specs passing
to reana-commons and docs.
Closes reanahub/reana-server/issues/113
> api: automatic openapi specs passing to reana-commons

- reana_commons/k8s/api_client.py
- reana_commons/version.py
- setup.py
* Since R-W-Controller connects now to Kubernetes as well we
centralise the initialisation in commons.
Connects reanahub/reana-workflow-controller#158.
> k8s: centralise Kubernetes client

- reana_commons/config.py
- reana_commons/consumer.py
- reana_commons/openapi_specifications/reana_server.json
- reana_commons/publisher.py
- reana_commons/tasks.py
- reana_commons/version.py
- setup.py
- tests/test_mq.py
- tests/test_tasks.py
* Adds workflow-submission queue to default queues.
Refactors configuration to allow for multiple default queues,
linked with their parameters.
Connects https://github.com/reanahub/reana/issues/119
Depends on https://github.com/reanahub/pytest-reana/pull/36
> consumer: workflow-submission queue

- reana_commons/tasks.py
* Stop workflow is fully implemented inside RWC now
(closes reanahub/reana-workflow-controller#157).
> tasks: remove stop workflow task

- reana_commons/api_client.py
- reana_commons/config.py
- reana_commons/openapi_specifications/reana_job_controller.json
* Adds dict with available CVMFS repositories in config.py,
which can be mounted in job pods.
* Updates openapi specs for job-controller, changing the
cvmfs_mounts parameter to boolean. If True, all CVMFS repos are
mounted.
Connect https://github.com/reanahub/reana-cluster/issues/154
> config: CVMFS repositories

- reana_commons/api_client.py
- reana_commons/openapi_specifications/reana_job_controller.json
- reana_commons/version.py
* Fixes default value for `cvmfs_mounts` in api_client.py.
* Fixes example for `cvmfs_mounts` in r-server openapi spec.
Connect https://github.com/reanahub/reana-cluster/issues/154
> api_client: cvmfs_mounts default value fix

- reana_commons/config.py
- reana_commons/k8s/api_client.py
- reana_commons/utils.py
- reana_commons/version.py
* Adds templates in config.py for creating CVMFS persistent volume
claims and storage classes. The templates take the CVMFS volume
as parameter and can be rendered by the utility methods added in
utils.py.
* Adds StorageV1Api kubernetes client for operating on storage
resources.
Connect https://github.com/reanahub/reana-cluster/issues/154
> global: pvc and sc templates, storagev1api client

- reana_commons/openapi_specifications/reana_job_controller.json
* Includes workflow_workspace as payload so RJC can determine the
relative path of the workflow workspace to mount on jobs.
> openapi: update RJC openapi spec

- reana_commons/api_client.py
- reana_commons/config.py
- reana_commons/openapi_specifications/reana_job_controller.json
config+api: add k8s default namespace & multiple job backends support
* Add config var for default K8s job namesapce. API changes for multiple
job bakend support.
Connects reanahub/reana-job-controller/issues/118
> config: add k8s default namespace

- reana_commons/api_client.py
- reana_commons/version.py
- setup.py
* Since we are enforcing HTTPS through self-signed certificates to
to access the REANA cluster we skip this verification for now
(closes reanahub/reana-cluster#174).
> api-client: verify SSL certificates off by default

- reana_commons/config.py
- reana_commons/version.py
* Setting default reana-server url for tests.
Connects reanahub/reana-client/issues/252
> config: setting default reana-server url

- reana_commons/utils.py
- reana_commons/version.py
- tests/test_utils.py
* When job controller and workflow engines run in the same pod,
workflow engine has to ensure that job controller is ready to
receive requests.
Connects reanahub/reana-job-controller/issues/105
> utils: adds function for connectivity test RWE->RJC

- reana_commons/config.py
- reana_commons/k8s/volumes.py
- reana_commons/version.py
* Storage backend types are lowercase strings, this caused interactive
sessions to not get the correct storage type, which in production means
interactive sessions get hostPath/local storage backend when it should
be CephFS.
> k8s: fix storage backend detection

- README.rst
- reana_commons/tasks.py
- reana_commons/version.py
- setup.py
* Removes usage of Celery in REANA, since serverless workflows Celery
is not used (closes reanahub/reana#188).
* Upgrades `kombu` version since once we merge Invenio branch into
REANA-Server master, the Celery version which Invenio requires,
requires itself bigger `kombu` version.
> installation: remove usage of Celery

- reana_commons/config.py
* REANA-Cluster is being deprecated so we are removing all references
to it (closes reanahub/reana#238).
> docs: remove reana-cluster references

- reana_commons/utils.py
- tests/test_utils.py
* Addresses reanahub/reana-client/issues/349
> utils: fixes CLI filtering

- reana_commons/config.py
- reana_commons/k8s/volumes.py
- reana_commons/tasks.py
- reana_commons/version.py
- Centralises CEPHFS PVC name 
- Passes correct boolean values to Kubernetes (for CVMFS and CEPHFS)
- Changes check for number of created jobs (in general) to number of REANA workflows created
> Fix cephfs and cvmfs

- reana_commons/api_client.py
- reana_commons/version.py
After https://github.com/reanahub/reana-commons/commit/068b5a693d6325da0729babea551aa16981cf912, the bravado client only instantiates once. This is perfectly fine when running the cluster under normal conditions (development or production), however when we want to patch some endpoints to mock their response in the tests, the instantiation (`make_mock_api_client()`) only happens [once](https://github.com/reanahub/pytest-reana/blob/master/pytest_reana/test_utils.py#L27), thus preventing the patch itself and making tests to fail. This happens in all the modules that install `reana-commons`: `reana-client`, `reana-server`, `reana-workflow-controller`, etc.
This PR fixes this problem and only re-instantiates the bravado client under some specific conditions that shouldn't affect at all the …
> global: fix bravado instantiation

- reana_commons/serial.py
Add kubernetes_uid field to serial workflow to allow user to specify the Kubernetes runtime user ID
closes reanahub/reana-workflow-engine-serial#106
> serial: add kubernetes_uid field

- reana_commons/api_client.py
- reana_commons/k8s/secrets.py
- reana_commons/openapi_specifications/reana_job_controller.json
- reana_commons/serial.py
Add grid proxy schema to serial workflow. Proxy certificate is added when user specifies `proxy: true` in reana.yaml.
closes reanahub/reana#256
> Grid proxy

- reana_commons/version.py
- setup.py
REANA-Commons uses `mock` in `api_client` therefore we need to include
it in installation dependencies.
Fixes problem of installing naked `reana-client` package without any
test libraries.
Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>
> installation: addition of mock

- reana_commons/email.py
- reana_commons/version.py
* Allows testing email notifications workflow locally
(addresses reanahub/reana#308).
(Adding closes here so it appears in kanban board)
Closes reanahub/reana#308
> mail: use authentication only if production

- CHANGES.rst
- reana_commons/config.py
- reana_commons/k8s/secrets.py
- reana_commons/version.py
* In order to be able to deploy REANA in different Kubernetes
namespaces we centralise the namespace configuration in
`REANA_INFRASTRUCTURE_KUBERNETES_NAMESPACE` so every REANA component
can rely on it when managing REANA related Kubernetes objects.
This configuration happends at deployment time
(closes reanahub/reana#274).
* Creates a new configuration variable to hold the namespace used
to run runtime pods in REANA (closes reanahub/reana#268).
* Creates a central configuration variable for fully qualified
infrastructure component names so any component can contact them
from a different namespace.
> config: centrally configured k8s namespace

- reana_commons/tasks.py
* Gets raw data from Kubernetes and avoids OpenAPI deserialization which
fails due to https://github.com/kubernetes-client/gen/issues/52,
even though [this fix](https://github.com/kubernetes/kubernetes/pull/85728)
exists, the Python Kubernetes library is still not compatible with it.
More information at https://github.com/kubernetes-client/python/issues/1174.
> tasks: skip client side node_list validation

- CHANGES.rst
- reana_commons/config.py
- reana_commons/version.py
* Needed by RWC and RJC to submit runtime pods to the correct nodes.
> config: load and parse runtime node label

- reana_commons/openapi_specifications/reana_server.json
- reana_commons/version.py
- openapi: sort reana-server specs
- release: 0.7.0a6
> fix openapi spec order

- setup.py
* Closes reanahub/pytest-reana#68.
> installation: mock upper bound as pytest-reana

- reana_commons/utils.py
GNU `du` default block size is KB so we have to pass `-b` to get bytes (raw).
closes reanahub/reana#437
> utils: fix get disk usage

- CHANGES.rst
- reana_commons/operational_options.py
Add `accept-metadir` as an operational option for Yadage. By passing `accept-metadir` you allow overwriting an existing meta directory `_yadage`.
closes reanahub/reana-server#293
> Add accept-metadir operational option

- .github/workflows/ci.yml
- reana_commons/publisher.py
- reana_commons/utils.py
- reana_commons/workflow_engine.py
* Implements a decorator to be used inside workflow engines code to
register workflows as failed if a termination signal is triggered
in the workflow engine environment. This is a defensive approach
because workflow engines are in charge of managing the workflow run
logic and if a termination signal has been triggered in their
running environment (container) there is no guarantee the workflow
will terminate successfully (the grace period is not known before
hand).
Addresses reanahub/reana#478
> utils: add decorator to handle termination signals

- CHANGES.rst
- reana_commons/config.py
- reana_commons/publisher.py
- reana_commons/version.py
- reana_commons/yadage.py
- setup.py
closes https://github.com/reanahub/reana-server/issues/358
This PR declares `workflow-submission` queue as a [priority queue](https://www.rabbitmq.com/priority.html).
With `RabbitMQ` there is an option `x-max-priority` to do that which takes as an argument positive integer between 1 and 255, indicating the maximum priority the queue should support. Value 0 is the default one and means no priority for the message.
With `kombu` there is [max-priority](https://docs.celeryproject.org/projects/kombu/en/stable/reference/kombu.html#kombu.Queue.max_priority) option to do that:
```
For example if the value is 10, then messages delivered to this queue can have a priority value between 0 and 10, where 10 is the highest priority.
```
I have also amended `publisher` classes to have an additional …
> publisher: prioritize workflows in the queue

- CHANGES.rst
- reana_commons/config.py
- reana_commons/publisher.py
- reana_commons/version.py
Creates a dedicated RabbitMQ exchange for a workflow submission with an ability to delay messages
Context: https://github.com/reanahub/reana-server/issues/118#issuecomment-854709746
PR is based on the instructions described in [RabbitMQ Delayed Message Plugin](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange)
Testing can be done in a similar way as described in [this issue](https://github.com/reanahub/reana-server/pull/366).
`reana_ready()` in scheduler could be set to always return `False` to constantly reschedule the messages. In this way it should be possible to check that the messages are delayed as expected.
Closes https://github.com/reanahub/reana-server/issues/118
> publisher: delay rescheduled workflows and count number of retries

- CHANGES.rst
- reana_commons/config.py
- reana_commons/publisher.py
- reana_commons/version.py
Reverts the changes done here: https://github.com/reanahub/reana-commons/commit/65836cdb3e9c7d23c15e2715dcd3cc75f9690c3c
> publisher: revert rescheduled workflows delay and remove number of retries

- reana_commons/config.py
- reana_commons/version.py
- reana_commons/workflow_engine.py
closes reanahub/reana-client#531
> snakemake: fix `load_operational_options_callback`

- AUTHORS.rst
- reana_commons/k8s/volumes.py
- reana_commons/openapi_specifications/reana_workflow_controller.json
- reana_commons/utils.py
- reana_commons/version.py
- reana_commons/workflow_engine.py
- reana_commons/yadage.py
- setup.py
Quit the dependency of upload-file,remove-file, list-files,mv-files  and download, relying directly on the full-path stored in the database
Closes reanahub/reana-db#94
> models: delete dependency on SHARED_VOLUME_PATH

- reana_commons/snakemake.py
- reana_commons/version.py
Load an internal representation of the Snakemake workflow, similar
to serial workflows, to ease the validation tasks.
closes reanahub/reana-client#540
> snakemake: parse snakefile rules

- .github/workflows/ci.yml
- reana_commons/operational_options.py
- reana_commons/version.py
- reana_commons/workflow_engine.py
- setup.py
- Include snakemake `reports` extra to install the dependencies needed.
closes #284
closes #288
> snakemake: add report operational option

- reana_commons/version.py
- setup.py
Due to problems when installing the `reports` deps in Ubuntu machines.
Plus, installing the `reports` deps is not needed for `reana-client`
as this feature is only used directly in the workflow engine.
> setup: make snakemake reports a separate extra

- reana_commons/config.py
- reana_commons/openapi_specifications/reana_server.json
- reana_commons/version.py
- reana_commons/workspaces.py
Goes on top of reanahub/reana-client#545 PR set, and reanahub/reana#532 PR set
Closes reanahub/reana-client#546
> workspaces: add validation function for the workflows 

- reana_commons/openapi_specifications/reana_server.json
Fixes small [syntax issues](https://github.com/reanahub/reana-server/actions/runs/1233012358) for [reana-server workspaces endpoint](https://github.com/reanahub/reana-server/pull/397)
> openapi: updated reana-server workspaces endpoint specification

- reana_commons/utils.py
closes reanahub/reana#530
Caused exceptions when running [`reana-demo-cms-h4l`](https://github.com/reanahub/reana-demo-cms-h4l) example with Snakemake, as it's not possible to get the time of last access (`st_atime`) of a symlink.
> utils: skip symlinks when creating `JobCache`

- reana_commons/version.py
- setup.py
closes #295
**To test:**
- Check that all examples run fine (`reana-dev run-example -w snakemake`), including `r-d-cms-h4l`.
> setup: upgrade snakemake version

- reana_commons/config.py
- reana_commons/snakemake.py
- reana_commons/version.py
closes reanahub/reana-workflow-engine-snakemake#13
> snakemake: adapt env validation to fallback image

- reana_commons/publisher.py
closes #305
After three unsuccessful retries, the `publish` call will fail. There is a possibility to add `try/catch` to:
https://github.com/reanahub/reana-commons/blob/86dd798259fbd7e5d4967a700243077fcc987012/reana_commons/publisher.py#L100-L107
I decided not to add `try/catch` here and leave the catching part (and decision what to do with it) on the calling code (basically, to engines). It is always possible to log an error and propagate further but I am not sure it is useful. Feel free to suggest a different option.
Testing:
1. start, for example, Yadage workflow
2. delete MQ pod using `kubectl delete pod` 
3. Check workflow-engine logs. You will see something similar:
```
2021-11-01 14:13:33,081 | reana-workflow-engine-yadage | MainThread | INFO | Workflow finished. Publishing... …
```
> publisher: log warning instead error when retrying publish

- tests/conftest.py
- tests/test_snakemake.py
Changes tests to use 256Mi instead of 64Mi. This is not really
necessary to do for tests, but it goes consistently in line with the
changes done in REANA demo examples, so that the old value of 64Mi
wouldn't pop up during grep etc in the code base.
> tests: use higher memory limit

- AUTHORS.rst
- setup.py
Resolves #322 for the time being by applying @tiborsimko's suggestion 1 from https://github.com/reanahub/reana-commons/issues/322#issuecomment-997282837
> 1. If adage/yadage packages use semantic versioning strictly, so that we can rely on a fact that 0.20.N will have the same API for any N, then we can perhaps pin in `r-commons` in a manner like ">=0.20,<0.21" and then have a strict pin "==0.20.1" in `r-w-e-yadage` only.
This also comes with the promise that @lukasheinrich and I will adhere to SemVer and not introduce API breaking changes in any patch releases of libraries in the [yadage GitHub org](https://github.com/yadage).
---
Use compatible release syntax to set lower bounds on patch releases and upper bounds on minor releases of:
* `adage>=0.10.1,<0.11.0`
* `yadage>=0.20.1,<0.21.0` …
> setup: Set compatible releases for dependencies in 'yadage' extra

- reana_commons/api_client.py
- reana_commons/openapi_specifications/reana_job_controller.json
closes reanahub/reana-job-controller#343
How to test:
This PR is part of a bigger group of PRs. Please refer to the addressed issue to find all of them.  It is important to check out the PR and update the` r-job-controller` image. Detailed instructions can be found in Yadage, Serial, CWL, and Snakemake PRs.
*thought:* `r-job-controller`'s OpenAPI specification is duplicated in this repository and in the `reana-job-controller` repository. Would make more sense to fetch it when the engine is starting directly from the job-controller endpoint `http://localhost:4000/openapi.json`.
> api_client: add kubernetes_job_timeout parameter

- .github/workflows/ci.yml
- CHANGES.rst
- LICENSE
- MANIFEST.in
- reana_commons/version.py
- setup.py
- tox.ini
Adds support for Python 3.10.
Removes `pathlib` PyPI installation dependency since it is now part of
the standard Python library as of Python 3.4 and since we dropped the
support for Python 2.7.
Adds initial Tox configuration to simplify local testing of multiple
Python versions.
Closes reanahub/reana#602.
> installation: support for Python 3.10

- CHANGES.rst
- reana_commons/utils.py
- replace "-b" option, that equals to "--block-size=1 --apparent-size", with just "--block-size=1" in "du" command;
- "--apparent-size" option calculates file size usage, but we need file system usage.
closes reanahub/reana-client#579
How to test?
1. Run a few different workflows on a `master` branch. Note used disk space for them. Check disk usage in the "Profile" tab.
2. Check out this PR, redeploy cluster, run a few different workflows. Note used disk space. Check disk usage in the "Profile" tab.
> utils: fix file system usage calculation in get_disk_usage

- setup.py
Set the compatible releases for the 'yadage' extra to support:
* `adage>=0.10.3,<0.11.0`
* `yadage>=0.20.2,<0.21.0`
as `adage` `v0.10.3` and `yadage` `v0.20.2` solidify support for modern `pydot` which is
required for use of the `networkx` `v2.0` API (`networkx` is `adage`'s only core dependency).
This will allow for
```console
python -m pip install 'yadage[viz]>=0.20.2'
```
to collect all additional dependencies needed for `yadage` related visualization with `graphviz` (though the `graphviz` libraries still need to exist).
This should help to avoid things like https://github.com/reanahub/reana-workflow-engine-yadage/issues/220.
<details>
<summary>Example:</summary>
```console
$ docker run --rm -ti python:3.9 /bin/bash
root@be73ad116cb7:/# apt update && apt install -y -qq graphviz …
```
> setup: Set compatible releases for 'yadage' extra to be support 'yadage[viz]'

- AUTHORS.rst
- reana_commons/config.py
Some Kubernetes variants (OpenShift, OKD) assign ephemeral UIDs.
In these cases, security contexts and switching user aren't
needed or allowed, and this variable should be set via the
same named environment variable to False.
> Add K8S_USE_SECURITY_CONTEXT config variable (default: True)

- CHANGES.rst
- reana_commons/openapi_specifications/reana_job_controller.json
- reana_commons/openapi_specifications/reana_server.json
- reana_commons/openapi_specifications/reana_workflow_controller.json
- reana_commons/version.py
- setup.py
Reverts changes done in https://github.com/reanahub/reana-commons/pull/333
addresses https://github.com/reanahub/reana-workflow-engine-yadage/issues/222
> release: 0.8.4

- CHANGES.rst
- reana_commons/publisher.py
- reana_commons/version.py
- because workflow submission publisher is used only in r-server, it makes sense to move it there;
closes reanahub/reana-server#436
> publisher: add retry count to workflow submission publisher

- CHANGES.rst
- reana_commons/k8s/api_client.py
- reana_commons/version.py
- setup.py
> Upgrade api client to networking v1 API

- CHANGES.rst
- docs/conf.py
- reana_commons/snakemake.py
- reana_commons/specification.py
- reana_commons/version.py
closes https://github.com/reanahub/reana-server/issues/456
Most of the workflow engines were not working (except `serial`) when launched from web UI. This is because the working directory is different when loading the specs and relative paths were no longer working. This PR fixes this issue by specifying different configs for each of the engine.
To test:
- Make sure that all the workflow engines are working both from the launcher and CLI
- To test `roofit` via launcher:
```
https://localhost:30443/launch?url=https://github.com/reanahub/reana-demo-root6-roofit.git&spec=reana.yaml&name=roofit-serial
https://localhost:30443/launch?url=https://github.com/reanahub/reana-demo-root6-roofit.git&spec=reana-yadage.yaml&name=roofit-yadage
https://localhost:30443/launch?url=https://github.com/reanahub …
```
> spec: improve spec loading functionality to support remote working directories

- reana_commons/openapi_specifications/reana_server.json
Updates the openapi disk usage specification, so that it can be more useful in `reana-client-go`
> openapi: updated reana-server openapi disk usage specification

- reana_commons/openapi_specifications/reana_server.json
closes https://github.com/reanahub/reana-client-go/issues/95
> openapi: add missing param schema to start_workflow

- reana_commons/openapi_specifications/reana_server.json
closes https://github.com/reanahub/reana-client-go/issues/96
> openapi: fix response schema of delete_file()

- reana_commons/openapi_specifications/reana_server.json
closes https://github.com/reanahub/reana-client-go/issues/97
> openapi: add missing response to move_files

- CHANGES.rst
- reana_commons/config.py
- reana_commons/k8s/kerberos.py
- reana_commons/version.py
closes https://github.com/reanahub/reana-job-controller/issues/375
Please note that `reanahub/reana-auth-krb5:1.0.1` image does not have `krenew` package. There is a [PR](https://github.com/reanahub/reana-auth-krb5/pull/8) to include it. Until it's merged and released testing could be done with `audrium/reana-auth-krb5:20221201` image specified [here](https://github.com/reanahub/reana-commons/blob/master/reana_commons/config.py#L484).
TODO:
> k8s: add krb5 sidecar container configuration to renew ticket

- CHANGES.rst
- reana_commons/k8s/kerberos.py
- reana_commons/version.py
closes https://github.com/reanahub/reana-job-controller/issues/375
> k8s: print timestamp in krb5 sidecar container when renewing ticket

- CHANGES.rst
- docs/conf.py
- reana_commons/consumer.py
- reana_commons/publisher.py
- reana_commons/version.py
- setup.py
- docs: switch to stable version of kombu
- docs: fix docstrings for kombu class references
- setup: bump upper pin of PyYAML
- release: 0.9.2.1
Closes https://github.com/reanahub/reana-commons/issues/399
> release 0.9.2.1

- CHANGES.rst
- reana_commons/openapi_specifications/reana_job_controller.json
- reana_commons/openapi_specifications/reana_server.json
- reana_commons/openapi_specifications/reana_workflow_controller.json
- reana_commons/version.py
- setup.py
- docs: switch to stable version of kombu
- docs: fix docstrings for kombu class references
- setup: bump upper pin of PyYAML
- release: 0.9.2.1
- openapi: update specs
- release: 0.9.3a4
Closes https://github.com/reanahub/reana-commons/issues/399
> global: merge maint-0.9

- .github/codecov.yml
- reana_commons/config.py
- reana_commons/openapi_specifications/reana_job_controller.json
- tests/conftest.py
Adds fully qualified canonical locations of container images, making the container technology setup podman-friendly.
Closes reanahub/reana#729.
> docker: podman-friendly image locations

- reana_commons/openapi_specifications/reana_server.json
- reana_commons/validation/utils.py
- reana_commons/version.py
- tests/test_validation.py
When validating the REANA specification, whitelist some keys in the JSON
schema (`additionalProperties`) that, when not correctly validated, will
issue a warning rather than raising a critical error.
The list of warnings is returned by the validator function.
Closes reanahub/reana-client#660
> validation: issue warning for extra keys in REANA specs

- reana_commons/email.py
- reana_commons/version.py
> email: don't send emails when notifications are disabled

- CHANGES.rst
- reana_commons/specification.py
- reana_commons/version.py
Change `load_reana_spec` by including two functions
`load_workflow_spec_from_reana_yaml` and `load_input_parameters` to
respectively load the workflow specification from the REANA yaml
dictionary and to load the CWL / Snakemake input parameters inside the
REANA specification dictionary from the workflow specification file.
Closes reanahub/reana-client#666
> specification: reformat load_reana_spec

- CHANGES.rst
- reana_commons/config.py
- reana_commons/k8s/volumes.py
- reana_commons/utils.py
- reana_commons/validation/schemas/reana_analysis_schema.json
- reana_commons/version.py
- tests/test_volumes.py
Remove the list of CVMFS repostiories to allow automounting of any CVMFS
repositorie provided by the user.
Closes #423
> utils: allow automounting of CVMFS repositories

- CHANGES.rst
- reana_commons/validation/schemas/reana_analysis_schema.json
- reana_commons/validation/utils.py
- reana_commons/version.py
- tests/test_validation.py
Closes reanahub/reana-client#679.
> validation: make environment property mandatory in serial steps

- reana_commons/config.py
- reana_commons/snakemake.py
- setup.py
- tests/conftest.py
- tests/test_snakemake.py
Update Snakemake version to v7.32.4 (latest one before v8 refactoring),
to support newer features and resolve problems for clients using Python 3.11.
- `reana_commons/config.py`: update default Snakemake environment image.
- `reana_commons/snakemake.py`: modify `first_rule` directive to
`default_target` directive to adhere to the changes made in
[snakemake/snakemake!638ec1a](https://github.com/snakemake/snakemake/tree/638ec1a983741cd7ba8faaf1a9dc76ae43d012e5).
- `setup.py`: adjust Snakemake version in the dependencies.
Closes: reanahub/reana-client#655.
Closes: reanahub/reana-workflow-engine-snakemake#31.
---
Note that, even though the external Snakemake API did not change, quite a few things
are different internally from v6.8.0 to v7.32.4, so proper testing is needed.
Also note that …
> fix(snakemake): update to v7.32.4 to make Python 3.11 clients compatible

- reana_commons/config.py
- reana_commons/k8s/kerberos.py
- perf(kerberos): stop ticket renewal immediately (#454)
Use `inotifywait` instead of `sleep` when waiting for the status file to
be created, so that the pod stops immediately after the file creation.
Closes https://github.com/reanahub/reana-job-controller/issues/450
- fix(kerberos): stop ticket renewal when pod is terminated (#453)
Closes https://github.com/reanahub/reana-job-controller/issues/449
> perf/fix(kerberos): kerberos ticket renewal improvements (#454)

- reana_commons/config.py
Remove hard-coded infrastructure component host name domain "svc.local.cluster", since this assumption is not really necessary and made REANA not to work under some deployment scenarios, such as on SSL-RIVER.
Closes #457
> fix(config): remove hard-coded component host name domain (#457)

- reana_commons/openapi_specifications/reana_server.json
- reana_commons/openapi_specifications/reana_workflow_controller.json
Closes reanahub/reana-server#690
> chore(openapi): update OpenAPI specifications (#460)

- pyproject.toml
- run-tests.sh
- setup.cfg
- setup.py
- tox.ini
- **ci(pytest): invoke `pytest` directly instead of `setup.py test` (#466)**
- **build(python): remove deprecated `pytest-runner` (#466)**
- **build(python): use optional deps instead of `tests_require` (#466)**
- **build(python): add minimal `pyproject.toml` (#466)**
Closes https://github.com/reanahub/reana/issues/814
> deprecations setuptools

- tox.ini
Fixes `tox` configuration with respect to installing all optional package dependencies that are necessary for running various tests.
Fixes `tox` collecting of code coverage information by forcing editable mode also in the test running instructions.
> ci(tox): fix collecting code coverage information

- .github/workflows/ci.yml
- AUTHORS.md
- setup.py
- tox.ini
Closes https://github.com/reanahub/reana/issues/837
Add support for Python 3.13.
> build(python): add support for Python 3.13 (#472)

- reana_commons/openapi_specifications/reana_server.json
- reana_commons/openapi_specifications/reana_workflow_controller.json
Related to https://github.com/reanahub/reana/issues/824
Update OpenAPI specifications: add `live_logs_enabled` to `reana-server` and `reana-workflow-controller` APIs.
> chore(openapi): update OpenAPI specifications (#473)

- reana_commons/openapi_specifications/reana_server.json
- reana_commons/validation/schemas/reana_analysis_schema.json
This pull request contains the ongoing work of dask integration into REANA.
> feat(dask): Dask integration (#467)

- .github/workflows/ci.yml
Pin `setuptools` to the maximum version of 70 to allow working on Ubuntu
20.04 LTS based environments. (New versions of `setuptools` are not
compatible.)
Note that this fix is necessary only for the `maint-0.9` branches and
the REANA 0.9 release series. In `master` we have switched to Ubuntu
24.04 LTS based environments and Python 3.12 and no pinning is necessary
there.
> ci(actions): pin setuptools 70 (#479)

- .github/workflows/ci.yml
- AUTHORS.md
- setup.py
- tox.ini
Closes reanahub/reana#837
Cherry-pick of #472
> build(python): add support for Python 3.13 (#480)

- reana_commons/utils.py
- tests/test_utils.py
Add a new function to get Dask component names from a central place instead of hard-coding them in different server components.
Closes reanahub/reana#841
> feat(utils): add central function for Dask K8s component names

- reana_commons/validation/schemas/reana_analysis_schema.json
- reana_commons/version.py
Following Dask integration into REANA, it became necessary for Dask clusters to be aware of if voms_proxy or rucio is needed for the whole workflow. Parsing each step in `reana.yaml` is not desirable, hence we add voms_proxy and rucio under global resources definition.
> Add Voms_proxy and Rucio under resources in reana.yaml schema

- reana_commons/openapi_specifications/reana_server.json
- reana_commons/validation/schemas/reana_analysis_schema.json
- reana_commons/version.py
Following the integration of Dask into REANA and discussions with several REANA users, we identified the need to make the number of threads configurable.
This commit introduces an additional field to allow users to specify the number of threads. The field is optional, similar to other Dask parameters, except for the image field.
The OpenAPI specification for the `api/info` command has been updated to include the default and maximum number of threads option for Dask workers.
Closes reanahub/reana#874
> feat(openapi): add fields for number of threads for Dask workers 

- reana_commons/api_client.py
- reana_commons/config.py
- reana_commons/errors.py
- reana_commons/job_utils.py
- reana_commons/openapi_specifications/reana_server.json
- reana_commons/validation/schemas/reana_analysis_schema.json
- tests/test_job_utils.py
Allow users to set CPU and memory requests/limits via `reana.yaml`. If not specified, default values configured by cluster admins will be applied.
Closes reanahub/reana#883
> feat(openapi): add K8s resource requests and limits in reana.yaml

- reana_commons/api_client.py
- reana_commons/config.py
- setup.py
- tests/test_utils.py
Replace `pkg_resources`` with the modern `importlib.resources` API to resolve deprecation warnings. Uses `importlib.resources`` for Python 3.9+ and the `importlib_resources` backport for Python 3.8 compatibility.
Closes #502
> refactor(config): replace deprecated pkg_resources
