.gitignore, AUTHORS.rst
=> docs: author ORCID links

reana_commons/models.py
* Changes name of `user` table to `user_` as it
clashes with postgres default naming.
Closes #7 
=> models: rename user table

reana_commons/config.py, reana_commons/models.py
* ADD Run, Job table in the models and their association table RunJobs.
=> models: addition of Job, Run tables

reana_commons/models.py, reana_commons/utils.py
* FIX default uuid assignment in the models. The generate_uuid method
will generate a new uuid each time an insertion occurs.
* ADD get_user_analysis_dir method, as it is used by reana-server and
reana-workflow-controller.
=> models: addition of generate_uuid method

reana_commons/utils.py, setup.py
=> installation: fs>=2.0

reana_commons/models.py
=> models: primary key fixes in Job, User tables

reana_commons/config.py
* (closes reanahub/reana-server#52).
=> config: default to postgres leave sqlite for tests

reana_commons/models.py
* Merges update_workflow_status and append_workflow_logs
=> models: save logs in update_workflow_status()

reana_commons/utils.py
Addesses https://github.com/reanahub/reana-server/issues/58
=> utils: analyses renaming to workflows

reana_commons/models.py
Connects https://github.com/reanahub/reana-client/issues/128
=> models: renaming api_key to access_token

reana_commons/models.py
Connects https://github.com/reanahub/reana-commons/issues/25
=> models: remove Organization and UserOrganization

reana_commons/models.py
* ADD step_name and prettified_cmd, to store information shown in
the UI or the CLI related to the job progress.
Connects https://github.com/reanahub/reana-client/issues/125
=> models: progress report related fields in Job

reana_commons/models.py
=> models: merge Workflow and Run tables

reana_commons/config.py, reana_commons/consumer.py, reana_commons/publisher.py
* ADD consumer.py publisher.py and config.py from
reana-workflow-commons, to merge the two repositories.
Connects https://github.com/reanahub/reana-workflow-commons/issues/4
=> global: merge reana-workflow-commons

AUTHORS.rst, CHANGES.rst, MANIFEST.in, docs/api.rst, docs/configuration.rst, docs/index.rst, reana_commons/config.py, reana_commons/consumer.py, reana_commons/publisher.py, reana_commons/utils.py, reana_commons/version.py, run-tests.sh, setup.py
=> global: release checklist

reana_commons/version.py
=> version: post-release bump

docs/conf.py, docs/index.rst, reana_commons/config.py, reana_commons/consumer.py, reana_commons/publisher.py, reana_commons/version.py, setup.py, tests/conftest.py, tests/test_mq.py, tests/test_version.py
=> mq: Kombu based consumer/producer and simple test

reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json
* Updates to latest openapi specifications for server and
workflow-controller, which include the reana_specification
parameter.
Connects https://github.com/reanahub/reana-db/issues/12
=> openapi: updated server and workflow-controller

reana_commons/version.py
=> release: 0.4.0.dev20181017

reana_commons/version.py
=> release: 0.4.0.dev20181105

reana_commons/utils.py, setup.py, tests/test_utils.py
Depends on https://github.com/reanahub/pytest-reana/pull/23
=> tests: utils

CHANGES.rst, reana_commons/version.py
=> REANA-Commons v0.4.0

reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json, reana_commons/serial.py
* New rest api endpoint which returns workflow input parameters.
Connects https://github.com/reanahub/reana-client/issues/200
=> api: new rest api endpoint

reana_commons/openapi_specifications/reana_workflow_controller.json
=> openapi: parameters object in set_workflow_status

reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json
* Closes reanahub/reana-client#210.
=> openapi: add delete_file endpoint

reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json, setup.py, tests/test_utils.py
Connects https://github.com/reanahub/reana-client/issues/193
=> openapi: updated specifications with diff

reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json, reana_commons/version.py
* Updating openapi specifications.
Connects reanahub/reana-workflow-engine-cwl/issues/69
=> openapi: Updating specs

reana_commons/api_client.py, reana_commons/config.py, reana_commons/errors.py, reana_commons/version.py
=> api: move the creation of open api clients to reana-commons

reana_commons/publisher.py, reana_commons/version.py
* Closes reanahub/reana-workflow-engine-yadage#98.
=> publisher: use new-style class declaration

reana_commons/config.py, reana_commons/utils.py
* Adds utility functions to format the messages pass to the MQ for
progress reporting.
Connects https://github.com/reanahub/reana-client/issues/234
=> utils: MQ message formatters

reana_commons/k8s/api_client.py
* Enable creation of Extensions/v1beta1 objects such as deployments
and ingress (addresses reanahub/reana-workflow-controller#178).
=> api: add k8s Extensions/v1beta1 client

reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json, reana_commons/version.py
Connects reanahub/reana-workflow-controller#178.
=> openapi: update specs for interactive nb's feature

reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json
* Connects reanahub/reana-client/issues/213
=> openapi: adding specs for mv files cmd

reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json, reana_commons/utils.py, reana_commons/version.py
* Adds utility function to retrieve the disk usage of
a workspace.
Connect https://github.com/reanahub/reana-client/issues/238
=> utils: workspace disk usage

reana_commons/utils.py, reana_commons/version.py
Connects https://github.com/reanahub/reana-client/issues/238
=> utils: fix disk usage summarize

reana_commons/k8s/__init__.py, reana_commons/utils.py, reana_commons/version.py
* Adds `__init__.py` in k8s directory.
=> k8s: mark as package directory

reana_commons/config.py, reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json
Closes https://github.com/reanahub/reana-client/issues/258.
=> config: centralise interactive session types

reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json
* Connects reanahub/reana-client/issues/247
=> openapi: new endpoint for closing an interactive session

reana_commons/config.py, reana_commons/k8s/volumes.py
Connects https://github.com/reanahub/reana-workflow-controller/issues/186.
=> k8s: centralise REANA k8s volume rendering

reana_commons/version.py
=> release: v0.5.0.dev20190314

reana_commons/config.py, setup.py
* Connects reanahub/reana-workflow-engine-cwl/issues/90
=> config: add default umask value

reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json, reana_commons/version.py, setup.py
* Query workflows by type (batch or interactive).
Connects reanahub/reana-client/issues/262
=> api: query workflows by type.

setup.py
=> setup: kombu/celery incompatibility fix

reana_commons/version.py
=> release: 0.5.0.dev20190322

reana_commons/config.py, reana_commons/version.py
=> logging: centralise log level and format config

setup.py
* (Closes #112)
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>
=> installation: remove upper boundaries for jsonschema

AUTHORS.rst, CHANGES.rst, README.rst, docs/api.rst, reana_commons/api_client.py, reana_commons/version.py, setup.py
* (closes #116)
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>
=> global: run release checklist

reana_commons/openapi_specifications/reana_job_controller.json
* Connects reanahub/reana-job-controller/issues/121
=> openapi: new field `backend` for RJC `delete_job` endpoint.

reana_commons/errors.py, reana_commons/k8s/secrets.py, reana_commons/openapi_specifications/reana_server.json, reana_commons/version.py, tests/conftest.py, tests/test_secrets_store.py
* Addresses reanahub/reana-server#138.
=> secrets: add secrets management class

reana_commons/k8s/secrets.py, reana_commons/version.py, setup.py, tests/conftest.py, tests/test_secrets_store.py
* Adresses reanahub/reana-job-controller#147
* In the future naming of the functions should be changed (TODO: issue for that)
=> secrets: add function to retrieve user secrets with it's value

reana_commons/version.py, setup.py
* Kubernetes 10.0.0 introduces breaking changes.
=> installation: pin kubernetes

reana_commons/api_client.py, reana_commons/config.py, reana_commons/k8s/secrets.py, reana_commons/openapi_specifications/reana_job_controller.json, reana_commons/serial.py, reana_commons/utils.py, reana_commons/version.py
=> serial: adds step's backend & name

reana_commons/config.py, reana_commons/k8s/secrets.py
* Closes reanahub/reana-workflow-controller#221
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>
=> secrets: extract all secret manipulation code

reana_commons/config.py
=> config: adds docstring for secrets mount path

AUTHORS.rst, reana_commons/config.py
Signed-off-by: Daniel Prelipcean <daniel.prelipcean@cern.ch>
=> config: add cvmfs for cms-opendata-conddb

AUTHORS.rst, reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json
* Updates REANA-Server and REANA-workflow-controller APIs
Signed-off-by: Leticia Farias Wanderley <leticia.farias.wanderley@cern.ch>
=> openapi: update api after gitlab integration

reana_commons/api_client.py, reana_commons/openapi_specifications/reana_job_controller.json, reana_commons/serial.py
=> serial: adds field kerberos to schema

setup.py
* Addresses reanahub/reana-client#320.
=> installation: upgrade jsonschema version

reana_commons/version.py, setup.py
=> setup: adds extra requires for jsonschema

reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json
* Closes reanahub/reana-client#302.
=> openapi: RWC and RS APIs supporting stream uploads

reana_commons/serial.py
* Addresses reanahub/reana-job-controller/issues/71
=> serial: allows slurmcern compute backend

reana_commons/config.py, reana_commons/k8s/volumes.py, reana_commons/version.py
* Moves SHARED_VOLUME_PATH conf var from RWC to RC.
Addresses reanahub/reana-workflow-controller/issues/231
=> config: adds SHARED_VOLUME_PATH

reana_commons/openapi_specifications/reana_server.json
addresses reanahub/reana-server#175
=> openapi: add gitlab integration endpoints

reana_commons/config.py, reana_commons/openapi_specifications/reana_job_controller.json, reana_commons/publisher.py, reana_commons/version.py
* Read from environment if EOS is available in the cluster and
store accross REANA how to mount EOS as a volume in Kubernetes
(closes reanahub/reana#216).
=> config: add EOS Kubernetes configuration

reana_commons/openapi_specifications/reana_server.json
addresses reanahub/reana-ui#38
=> openapi: add gitlab hook deletion endpoint

reana_commons/config.py, reana_commons/k8s/api_client.py
* Addresses reanahub/reana-workflow-controller#267.
=> api_client: add new API for Ingresses

reana_commons/api_client.py, reana_commons/openapi_specifications/reana_job_controller.json, reana_commons/version.py
* Addresses reanahub/reana-workflow-controller/issues/269
=> api: cleans RJC api & allows to set uid for yadage jobs

AUTHORS.rst, CHANGES.rst, CONTRIBUTING.rst, reana_commons/version.py, setup.py, tests/conftest.py, tests/test_mq.py, tests/test_tasks.py, tests/test_version.py
Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>
=> release: v0.6.0

reana_commons/config.py, setup.py
=> config: prepend REANA prefix to components

reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json, reana_commons/utils.py, reana_commons/version.py
addresses reanahub/reana-client#341
=> utils: allow getting robot-friendly usage information

reana_commons/openapi_specifications/reana_workflow_controller.json
* Addresses reanahub/reana#253.
=> openapi: RWC return 502 on external failures

reana_commons/config.py
closes reanahub/reana-server#203
=> logs: increase log level to INFO

reana_commons/config.py
=> config: update to latest cvmfs csi driver

reana_commons/version.py
=> release: 0.7.0.dev20200129

reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json
=> openapi: add run start and finish times

reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json
* Addresses reanahub/reana-client/issues/369
=> openapi: adds a possibility to query logs for a given step

reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json, reana_commons/version.py
=> openapi: add preview flag to download_file()

reana_commons/openapi_specifications/reana_server.json, reana_commons/version.py
closes reanahub/reana-client#383
=> rest: allow access_token param in /api/me

reana_commons/api_client.py
* Closes reanahub/reana-server#225.
=> api_client: instantiate bravado client only once

reana_commons/version.py, setup.py
=> global: bump to kubernetes 11

reana_commons/api_client.py, reana_commons/openapi_specifications/reana_job_controller.json, reana_commons/serial.py
* Addresses reanahub/reana-job-controller/issues/238
=> serial: allows to specify unpacked image

reana_commons/config.py, reana_commons/k8s/secrets.py, reana_commons/k8s/volumes.py, reana_commons/publisher.py, reana_commons/utils.py
Closes reanahub/docs.reana.io#18.
=> config: add component prefix configuration

reana_commons/errors.py, reana_commons/operational_options.py, reana_commons/serial.py, reana_commons/version.py, tests/test_operational_options.py
closes reanahub/reana-client#396
=> global: workflow operational options validation

reana_commons/email.py, reana_commons/version.py
closes reanahub/reana-server#235
=> mail: add new util to send emails

reana_commons/openapi_specifications/reana_server.json
=> openapi: add request token endpoint

setup.py
Fixes #180.
Updating kubernetes version. I did not change reana-commons version number [here](https://github.com/reanahub/reana-commons/blob/maint-0.6/reana_commons/version.py#L17) though, let me know if I should.
=> Update kubernetes client.

AUTHORS.rst, CHANGES.rst, reana_commons/version.py
Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>
=> release: v0.6.1

reana_commons/openapi_specifications/reana_server.json
=> openapi: update /me and /token endpoints

reana_commons/email.py, reana_commons/version.py
=> email: add 'From' and 'To' headers

CHANGES.rst, README.rst, docs/conf.py, pytest.ini, reana_commons/__init__.py, reana_commons/api_client.py, reana_commons/config.py, reana_commons/consumer.py, reana_commons/email.py, reana_commons/errors.py, reana_commons/k8s/api_client.py, reana_commons/k8s/secrets.py, reana_commons/k8s/volumes.py, reana_commons/operational_options.py, reana_commons/publisher.py, reana_commons/serial.py, reana_commons/tasks.py, reana_commons/utils.py, run-tests.sh, setup.py, tests/test_mq.py, tests/test_operational_options.py, tests/test_secrets_store.py, tests/test_tasks.py, tests/test_utils.py, tests/test_version.py
=> global: Black support

reana_commons/config.py, reana_commons/errors.py, reana_commons/openapi_specifications/reana_server.json, setup.py
=> openapi: add config endpoint

reana_commons/openapi_specifications/reana_server.json
closes reanahub/reana-server#256
=> rest: rename get_me to get_you

AUTHORS.rst, CHANGES.rst, reana_commons/operational_options.py
Add operational options `initfiles`
closes reanahub/reana#305
=> Operational options: add initfiles

reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json, reana_commons/version.py
closes reanahub/reana-server#180
=> openapi: add pagination args

reana_commons/email.py, reana_commons/errors.py, reana_commons/version.py, tests/test_email.py
=> email: detect missing mail connection config

reana_commons/utils.py, setup.py
=> utils: provide disk usage per user

reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json, reana_commons/version.py
closes https://github.com/reanahub/reana-ui/issues/132
=> openapi: workflows filtering parameters

reana_commons/openapi_specifications/reana_server.json, reana_commons/version.py
* Closes reanahub/reana-server#289.
* Removes unused endpoints to create and get users.
=> openapi: overall user quota usage with limits

docs/requirements.txt
=> docs: install only docs required dependencies for RTD build

reana_commons/openapi_specifications/reana_server.json, setup.py
=> global: fix typo

reana_commons/openapi_specifications/reana_server.json
* Closes reanahub/reana-server#296.
=> openapi: return human-readable quota values

reana_commons/utils.py
Adds the option to define the color of the output. Useful when printing quota usage.
Closes reanahub/reana-server#284
=> utils: add colours to table printer

reana_commons/config.py, reana_commons/version.py
closes reanahub/reana-client#424
=> util: add resource health color mapping

reana_commons/errors.py, reana_commons/utils.py, reana_commons/version.py
* Closes reanahub/reana-db#100.
=> utils: du new custom exception on missing dir

reana_commons/openapi_specifications/reana_workflow_controller.json
closes reanahub/reana-client#436
=> openapi: remove workflow hard deletion option

reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json, reana_commons/utils.py, reana_commons/version.py
* Closes reanahub/reana-server#296.
=> openapi: human_readable option to show disk usage

reana_commons/errors.py, reana_commons/version.py
closes reanahub/reana-server#282
=> errors: add quota exceeded exception 

.github/workflows/ci.yml, setup.py
=> ci: added python 2.7 to github action python test strategy

CHANGES.rst, reana_commons/api_client.py, reana_commons/config.py, reana_commons/openapi_specifications/reana_job_controller.json, reana_commons/serial.py, reana_commons/utils.py
Add `htcondor_max_runtime` and `htcondor_accounting_group`
Closes reanahub/reana-job-controller#32
=> HTC resources

CHANGES.rst, reana_commons/openapi_specifications/reana_server.json, reana_commons/version.py
closes https://github.com/reanahub/reana-client/issues/441
=> openapi: return reana_server_version

.flake8, .github/workflows/ci.yml, MANIFEST.in, reana_commons/errors.py, reana_commons/k8s/secrets.py, reana_commons/utils.py, run-tests.sh, setup.py, tests/test_secrets_store.py, tests/test_utils.py
addresses https://github.com/reanahub/reana/issues/456
=> ci: added flake8 linter

.github/workflows/ci.yml, docs/conf.py, reana_commons/openapi_specifications/reana_server.json
=> openapi: control ui signup form visibility with through config endpoint

reana_commons/openapi_specifications/reana_server.json
=> openapi: add invenio confirm endpoints

CHANGES.rst, reana_commons/config.py, reana_commons/version.py
* Addresses reanahub/reana#461.
=> config: add job cleanup configuration

CHANGES.rst, reana_commons/api_client.py, reana_commons/job_utils.py, reana_commons/version.py, setup.py, tests/test_job_utils.py
* Closes reanahub/reana-job-controller#304
=> global: harmonise job command string treatment

CHANGES.rst, reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json, reana_commons/version.py
closes reanahub/reana-client#225
=> openapi: support glob patterns when listing files

reana_commons/config.py, reana_commons/version.py
Closes reanahub/reana#493.
Will pass once https://github.com/reanahub/reana-db/pull/123 gets merged.
=> config: split runtime node labels

reana_commons/config.py, reana_commons/k8s/api_client.py, reana_commons/openapi_specifications/reana_server.json, reana_commons/version.py
closes reanahub/reana#501
closes reanahub/reana-ui#183
=> k8s: add custom objects API instance to k8s client

reana_commons/version.py, reana_commons/workflow_engine.py, reana_commons/yadage.py
Making https://github.com/reanahub/reana-client/pull/518 tests to fail.
=> global: remove f-strings

reana_commons/k8s/api_client.py, reana_commons/yadage.py
Closes reanahub/reana-server#356
=> global: remove unused import

reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json
- api-schema: add search type in /workspace
closes https://github.com/reanahub/reana-client/issues/521
=> Add search param in schema

reana_commons/version.py, setup.py
closes reanahub/reana-workflow-engine-yadage#192
=> setup: pin `adage` in yadage extra

reana_commons/utils.py
closes https://github.com/reanahub/reana-client/issues/522
=> utils: add filter in calculating disk usage info

.github/workflows/ci.yml, CHANGES.rst, reana_commons/snakemake.py, reana_commons/workflow_engine.py, setup.py
closes reanahub/reana-client#531
=> snakemake: add spec load & validate function

reana_commons/config.py, reana_commons/k8s/volumes.py, reana_commons/workspaces.py
=> config: create dictionary of host and mounted paths

reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json, reana_commons/version.py
Closes reanahub/reana-client#452
=> openapi: add workflow as parameter of get_workflows used as a filter

reana_commons/config.py, reana_commons/utils.py, reana_commons/version.py, setup.cfg
closes https://github.com/reanahub/reana-commons/issues/301
=> config: new config for job controller connection check sleep

reana_commons/openapi_specifications/reana_server.json, setup.py
closes https://github.com/reanahub/reana-ui/issues/206
=> openapi: updated reana-server status endpoint specification

CHANGES.rst, reana_commons/config.py, reana_commons/validation.py, reana_commons/version.py
closes [reanahub/reana-client#584](https://github.com/reanahub/reana-client/issues/584)
=> validation: added workspace name validation utility

reana_commons/api_client.py
closes reanahub/reana-job-controller#343
=> api_client: allow zero value in kubernetes_job_timeout

CHANGES.rst, reana_commons/openapi_specifications/reana_server.json, reana_commons/snakemake.py, reana_commons/version.py
closes reanahub/reana-workflow-controller#424
=> snakemake: add compute backend to snakemake loaded specification

CHANGES.rst, reana_commons/version.py, setup.py
Related https://github.com/reanahub/reana-server/pull/429
=> setup: remove upper bound on kombu version

CHANGES.rst, reana_commons/openapi_specifications/reana_server.json
=> openapi: add launch-on-reana endpoint

reana_commons/openapi_specifications/reana_workflow_controller.json
=> openapi: include `launcher_url` in workflow properties

reana_commons/openapi_specifications/reana_server.json
Closes reanahub/reana-server#452
=> openapi: update reana-server launch endpoint

reana_commons/validation/compute_backends.py
Closes reanahub/reana-workflow-engine-cwl#222
=> validation: fix accidental removal of cwl hints

reana_commons/openapi_specifications/reana_server.json
closes https://github.com/reanahub/reana-server/issues/479
=> openapi: updated reana-server openapi specification

CHANGES.rst, reana_commons/api_client.py, reana_commons/openapi_specifications/reana_job_controller.json, reana_commons/serial.py
closes https://github.com/reanahub/reana-job-controller/issues/206
=> slurm: expose some of the job configuration to users

reana_commons/utils.py, reana_commons/version.py
closes https://github.com/reanahub/reana-client/issues/607
=> utils: port quota resource usage util from r-client

reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json
Closes reanahub/reana-server#418
=> openapi: update specifications

CHANGES.rst, reana_commons/validation/schemas/reana_analysis_schema.json, tests/test_validation.py
Closes reanahub/reana-client#617
=> schemas: add `retention_days` to specification of `reana.yaml`

reana_commons/openapi_specifications/reana_workflow_controller.json, reana_commons/version.py
Closes https://github.com/reanahub/reana/issues/653
=> openapi: update r-w-c spec to allow workflows without retention rules

reana_commons/openapi_specifications/reana_server.json
closes https://github.com/reanahub/reana-client-go/issues/16
=> openapi: add missing schemas to error responses

reana_commons/openapi_specifications/reana_server.json
closes https://github.com/reanahub/reana-client-go/issues/30
closes https://github.com/reanahub/reana-client-go/issues/20
=> cli: add openapi specification for progress in get_workflow_status and missing error schema

reana_commons/openapi_specifications/reana_server.json, reana_commons/version.py
closes reanahub/reana-client#622
=> openapi: add additional values to "info" endpoint

reana_commons/openapi_specifications/reana_server.json
closes https://github.com/reanahub/reana-client-go/issues/93
=> openapi: add missing param schema do set_workflow_status

AUTHORS.rst, CHANGES.rst, reana_commons/api_client.py, reana_commons/openapi_specifications/reana_job_controller.json, reana_commons/serial.py
Closes reanahub/reana-auth-rucio#1.
=> serial: add field rucio to schema

reana_commons/openapi_specifications/reana_server.json
closes https://github.com/reanahub/reana-client-go/issues/131
=> openapi: add missing workflow spec schema to get_workflow_specification

reana_commons/openapi_specifications/reana_server.json
~~Related to https://github.com/reanahub/reana-server/pull/551~~
=> openapi: update get_workflow_specification of reana-server

reana_commons/errors.py, reana_commons/version.py, reana_commons/workspace.py, tests/test_workspace.py
Closes https://github.com/reanahub/reana-server/issues/559
=> workspace: move from reana-workflow-controller

reana_commons/version.py, reana_commons/workspace.py, setup.py, tests/test_workspace.py
=> workspace: support recursive globbing

reana_commons/openapi_specifications/reana_server.json, reana_commons/openapi_specifications/reana_workflow_controller.json, reana_commons/version.py
Closes https://github.com/reanahub/reana-workflow-controller/issues/485
=> openapi: add `get_workflow_retention_rules` endpoint

reana_commons/openapi_specifications/reana_server.json
Closes reanahub/reana-server#252
=> openapi: update `gitlab_oauth` of reana-server

CHANGES.rst, LICENSE, docs/conf.py, reana_commons/specification.py, tests/test_specification.py
Closes reanahub/reana-workflow-engine-snakemake#55
=> spec: fix loading specification without parameters

CHANGES.rst, docs/conf.py, reana_commons/email.py
=> email: allow customisation of SSL/STARTTLS

CHANGES.rst, reana_commons/consumer.py, reana_commons/publisher.py, reana_commons/validation/schemas/reana_analysis_schema.json
closes https://github.com/reanahub/reana-server/issues/597
=> schemas: enrich reana JSON schema to allow specifying Gherkin feature files

CHANGES.rst, reana_commons/openapi_specifications/reana_server.json
Closes reanahub/reana-client#657.
=> openapi: add inactivity period to info endpoint

CHANGES.rst, reana_commons/openapi_specifications/reana_server.json
=> openapi: add run_stopped_at to status endpoint

CHANGES.rst, reana_commons/config.py, reana_commons/utils.py
Set the correct namespace for CVMFS's PersistentVolumeClaim.
Closes #412
=> utils: set correct namespace for CVMFS deployment

CHANGES.rst, reana_commons/version.py, setup.py
- setup: set upper bound on bravado-core
- release: 0.9.5
=> setup: set upper bound on bravado-core

reana_commons/config.py
Closes reanahub/reana-workflow-controller#561
=> feat(config): allow customisation of runtime group name (#440)

AUTHORS.md, setup.py
Closes reanahub/reana-client#706
=> build(snakemake): require pulp<2.8.0 (#444)

AUTHORS.md, reana_commons/api_client.py, reana_commons/openapi_specifications/reana_job_controller.json, reana_commons/serial.py, reana_commons/validation/schemas/reana_analysis_schema.json
This pull request allows for validation of the new `compute4punch` compute backend, being currently implemented in https://github.com/reanahub/reana-job-controller/pull/430.
=> Add support for compute4punch backend

.github/workflows/ci.yml, setup.py, tests/test_workspace.py
BREAKING CHANGE: drop support for Python 3.6 and 3.7
Closes reanahub/reana#784
=> build(python): drop support for Python 3.6 and 3.7 (#453)

AUTHORS.md, MANIFEST.in, reana_commons/gherkin_parser/__init__.py, reana_commons/gherkin_parser/data_fetcher.py, reana_commons/gherkin_parser/errors.py, reana_commons/gherkin_parser/functions.py, reana_commons/gherkin_parser/parser.py, setup.py, tests/conftest.py, tests/gherkin_test_files/features/expected-failure.feature, tests/gherkin_test_files/features/failing-test.feature, tests/gherkin_test_files/features/log-content.feature, tests/gherkin_test_files/features/test-gherkin-syntax.feature, tests/gherkin_test_files/features/workflow-duration.feature, tests/gherkin_test_files/features/workflow-execution-completes.feature, tests/gherkin_test_files/features/workspace-content.feature, tests/test_gherkin_functions.py, tests/test_gherkin_parser.py
=> feat(gherkin-parser): add parser and required functions (#464)

reana_commons/openapi_specifications/reana_server.json
closes https://github.com/reanahub/reana/issues/834
=> feat(openapi): add dask_autoscaler_enabled field

reana_commons/openapi_specifications/reana_server.json
Closes reanahub/reana-workflow-controller#569
=> feat(openapi): add recommended images to info endpoint

reana_commons/openapi_specifications/reana_server.json
Closes reanahub/reana-client#734
=> feat(openapi): add engine versions to info endpoint
